dist: trusty
sudo: required
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
  - cmake --build .
  - ./test/fsm_test/fsm_UnitTest
  - ./test/hsm_test/hsm_UnitTest
 
