dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7 

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-7 cmake .
  - cmake --build .