dist: trusty
sudo: required
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .  
  - cmake --build .
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - ./test/fsm_test/fsm_UnitTest
  - ./test/fsm_test/hsm_UnitTest
 
